language: python
install:
  - pip install ansible-lint
script: ansible-lint .

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
