---

- name: Install PHP-FPM
  apt:
    name:
      - "php{{ php_version }}-fpm"

- name: Install PHP modules
  apt:
    name:
      - "php{{ php_version }}-{{ item }}"
  with_items: "{{ php_modules }}"
  notify: reload php-fpm

- name: Remove default FPM pool
  file:
    state: absent
    path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  when: php_fpm_default_pool_enabled == false

- name: Configure FPM pools
  template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ pool.name }}.conf"
  vars: 
    pool: "{{php_fpm_pool_defaults | combine(pool_)}}"
  loop: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: pool_
  notify: reload php-fpm
  tags: php-fpm.pools
